import { useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, Building07, Globe02, Scale01, Coins01, Users01, LayersThree01, ShieldTick, Check, Compass03, XClose, MarkerPin01 } from '@untitledui/icons';
import { Modal, ModalOverlay, Dialog, Heading as DialogHeading, Button as AriaButton } from 'react-aria-components';
import { locales, initialLanguage, type Language } from './locales';
import { Header } from './components/header';
import { Footer } from './components/footer';
import { Badge, Button, Heading, Card, ServiceCard, TimelineStep, FormField } from './components/ui';
import { ConnectionVisual } from './components/connection-visual';
import './App.css';
const icons = [Building07, Scale01, Coins01, Users01, Globe02, LayersThree01];
function App() {
  const [language, setLanguage] = useState<Language>(initialLanguage);
  const [modal, setModal] = useState<'contact' | 'privacy' | 'terms' | 'linkedin' | null>(null);
  const [prepared, setPrepared] = useState(false);
  const t = locales[language];
  useEffect(() => {
    document.documentElement.lang = language;
    document.title = `Nordion | ${t.hero}`;
    document.querySelector('meta[name="description"]')?.setAttribute('content', t.intro);
    try { localStorage.setItem('nordion-language', language); } catch { /* Optional persistence. */ }
  }, [language, t]);
  return <><a className="skip-link" href="#main">{t.skip}</a><Header t={t} language={language} onLanguage={setLanguage}/><main id="main">
    <section id="inicio" className="hero-section"><div className="container hero-grid"><div className="hero-copy"><Badge>{t.eyebrow}</Badge><h1>{t.hero}<br/><span>{t.heroAccent}</span></h1><p>{t.intro}</p><div className="button-row"><Button href="#contato">{t.primary}</Button><a className="text-link" href="#sobre">{t.secondary}<ArrowRight size={17}/></a></div><div className="hero-note"><ShieldTick size={18}/>{t.heroNote}</div></div><ConnectionVisual t={t}/></div><div className="container trust-strip">{t.pillars.map((p, i) => <span key={p}>{i === 0 ? <Compass03/> : i === 1 ? <LayersThree01/> : <ShieldTick/>}{p}</span>)}<span className="trust-end">GLOBAL THINKING. LOCAL EXPERTISE. <ArrowUpRight size={17}/></span></div></section>
    <section className="section problem-section"><div className="container"><div className="split-heading"><Heading label={t.problemLabel} title={t.problemTitle}/><p>{t.problemText}</p></div><div className="grid four">{t.problems.map((title, i) => { const Icon = [Scale01, Coins01, Users01, Building07][i]; return <Card key={title} className="problem-card"><Icon size={25}/><h3>{title}</h3><span className="small-arrow">↗</span></Card>; })}</div></div></section>
    <section className="value-section"><div className="container value-grid"><div><Heading label={t.valueLabel} title={t.valueTitle} text={t.valueText}/><p className="value-quote">{t.valueQuote}</p></div><div className="journey">{t.journey.map((item, i) => <div key={item} className={`journey-node node-${i}`}><span>{i === 0 ? <Building07/> : i === 1 ? <Compass03/> : <Globe02/>}</span><strong>{item}</strong>{i < 2 && <ArrowRight className="journey-arrow"/>}</div>)}</div></div></section>
    <section id="como-funciona" className="section"><div className="container"><Heading label={t.processLabel} title={t.processTitle} text={t.processText} centered/><ol className="timeline">{t.steps.map(([title, text], i) => <TimelineStep key={title} number={i + 1} title={title} text={text}/>)}</ol></div></section>
    <section id="servicos" className="section services-section"><div className="container"><div className="split-heading"><Heading label={t.servicesLabel} title={t.servicesTitle}/><p>{t.servicesText}</p></div><div className="grid three">{t.services.map(([title, text], i) => { const Icon = icons[i]; return <ServiceCard key={title} icon={<Icon size={24}/>} title={title} text={text} number={i + 1}/>; })}</div><p className="partners-note"><ShieldTick size={20}/>{t.partners}</p></div></section>
    <section className="section"><div className="container"><Heading label={t.differenceLabel} title={t.differenceTitle} text={t.differenceText} centered/><div className="comparison"><Card className="traditional"><span className="eyebrow">{t.traditional}</span><div className="company-node"><Building07 size={22}/>{t.journey[0]}</div><div className="supplier-grid">{t.suppliers.map(s => <span key={s}>{s}</span>)}</div><p>{t.fragmented}</p></Card><Card className="integrated"><span className="eyebrow">{t.integrated}</span><div className="company-node"><Building07 size={22}/>{t.journey[0]}</div><div className="coordination-node"><Compass03 size={22}/>nordion.</div><div className="supplier-grid">{t.suppliers.map(s => <span key={s}>{s}</span>)}</div><p><Check size={17}/>{t.coordinated}</p></Card></div></div></section>
    <section id="brasil" className="brazil-section"><div className="container brazil-grid"><div className="brazil-art" aria-hidden="true"><div className="brazil-orbit"/><svg viewBox="0 0 340 360"><path d="m105 47 26 9 19-15 18 13 15-14 20 25 18 5 18-10 10 29 30 8 14 24 32 9-5 35-23 19-16 29-16 12-8 36-29 27-17 27-17 19-12-29 11-21-24-18-18-32-26-4-11-25-29-9-16-25 10-20-11-14 18-23 1-32 23 4Z" fill="#477c70" stroke="#8eaea0" strokeWidth="1"/><path d="m108 117 117 118M216 116 142 248M79 169l164 30" stroke="#a3c0ab" strokeDasharray="3 5" fill="none"/><circle cx="225" cy="235" r="20" fill="#D6AE61" fillOpacity=".15"/><circle cx="225" cy="235" r="5" fill="#D6AE61"/></svg><span className="brazil-art-label"><MarkerPin01 size={18}/>{t.brazil}<ArrowUpRight size={18}/></span><span className="art-coordinate">14° S &nbsp; 51° W</span></div><div><Heading label={t.brazilLabel} title={t.brazilTitle} text={t.brazilText}/><ul className="opportunities">{t.opportunities.map(o => <li key={o}><ArrowUpRight size={20}/>{o}</li>)}</ul></div></div></section>
    <section className="section"><div className="container"><Heading label={t.audienceLabel} title={t.audienceTitle} centered/><div className="grid three audiences">{t.audiences.map((title, i) => { const Icon = [Globe02, Building07, Users01][i]; return <Card key={title}><span className="icon-box"><Icon/></span><h3>{title}</h3><a href="#contato" aria-label={`${t.ctaPrimary}: ${title}`}><ArrowUpRight/></a></Card>; })}</div></div></section>
    <section className="scenario-section"><div className="container scenario-box"><div><Heading label={t.scenarioLabel} title={t.scenarioTitle}/><p>{t.scenarioText}</p><h3>{t.scenarioAnswer}</h3></div><div><ol className="scenario-path">{t.scenarioSteps.map((s, i) => <li key={s}><span>{i === 4 ? <Check size={16}/> : `0${i + 1}`}</span>{s}{i < 4 && <ArrowRight size={16}/>}</li>)}</ol><p className="scenario-note">{t.scenarioNote}</p></div></div></section>
    <section id="sobre" className="section"><div className="container about-grid"><Heading label={t.aboutLabel} title={t.aboutTitle}/><div><p className="about-text">{t.aboutText}</p><div className="values">{t.values.map(v => <span key={v}><Check size={15}/>{v}</span>)}</div></div></div></section>
    <section id="contato" className="cta-section"><div className="container cta-inner"><span className="eyebrow">{t.ctaLabel}</span><h2>{t.ctaTitle}</h2><p>{t.ctaText}</p><div className="button-row"><Button onClick={() => { setPrepared(false); setModal('contact'); }}>{t.ctaPrimary}</Button><Button href="#como-funciona" secondary>{t.ctaSecondary}</Button></div><span className="cta-decoration" aria-hidden="true">↗</span></div></section>
  </main><Footer t={t} onInfo={setModal}/>
  <ModalOverlay className="modal-overlay" isOpen={modal !== null} onOpenChange={open => { if (!open) setModal(null); }} isDismissable><Modal className="modal"><Dialog className="dialog"><AriaButton className="modal-close" aria-label={t.close} onPress={() => setModal(null)}><XClose/></AriaButton><DialogHeading slot="title">{modal === 'contact' ? t.contactTitle : modal === 'privacy' ? t.privacy : modal === 'terms' ? t.terms : 'LinkedIn'}</DialogHeading>{modal === 'contact' ? <><p>{t.contactText}</p><form onSubmit={e => { e.preventDefault(); setPrepared(true); }}><FormField name="name" label={t.name}/><FormField name="email" label={t.email} type="email"/><FormField name="business" label={t.business}/><FormField name="message" label={t.message} multiline/><p className="form-note">{t.contactNote}</p><button className="button" type="submit">{t.send}<ArrowUpRight size={18}/></button>{prepared && <p role="status" className="success-message">{t.success}</p>}</form></> : <p>{modal === 'privacy' ? t.privacyText : modal === 'terms' ? t.termsText : t.linkedinText}</p>}</Dialog></Modal></ModalOverlay>
  </>;
}
export default App;
